import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { BasicLayout } from "../layouts/BasicLayout"
import styles from "../styles/Home.module.css"

const SellNft: NextPage = () => {
  return (
    <BasicLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        meow
      </div>
    </BasicLayout>
  )
}

export default SellNft
